#!/usr/bin/env npx tsx
/**
 * Content generation script — builds the expanded wisdom corpus.
 * Generates: 100+ Gita, 50+ Stoic, 30+ Buddhist, 20+ Yoga Sutras verses,
 * 70+ affirmations, 15+ meditation templates.
 *
 * Run: npx tsx scripts/generate-content.ts > src/data/wisdom-expanded.ts
 */

// ==========================================
// GITA VERSES (100 key verses from 18 chapters)
// ==========================================
const gitaVerses = [
  // Chapter 1 - Arjuna's Dilemma
  { ref: "1.1", text: "Dhritarashtra said: O Sanjaya, assembled in the holy field of Kurukshetra and desiring to fight, what did my sons and the sons of Pandu do?", themes: ["duty", "conflict", "beginning"], moods: ["confused", "anxious"] },
  { ref: "1.47", text: "Sanjaya said: Having spoken thus, Arjuna cast aside his bow and arrows and sat down on the chariot, his mind overwhelmed with grief.", themes: ["grief", "overwhelm", "paralysis"], moods: ["sad", "overwhelmed", "confused"] },

  // Chapter 2 - The Yoga of Knowledge
  { ref: "2.3", text: "Do not yield to unmanliness, O Arjuna. It does not befit you. Shake off this petty faint-heartedness and arise, O scorcher of enemies!", themes: ["courage", "action", "strength"], moods: ["sad", "frustrated", "overwhelmed"] },
  { ref: "2.11", text: "The wise grieve neither for the living nor for the dead. There was never a time when I did not exist, nor you, nor these rulers of men; nor shall any of us cease to exist in the future.", themes: ["impermanence", "wisdom", "perspective"], moods: ["sad", "lonely", "anxious"] },
  { ref: "2.14", text: "The contact between the senses and their objects gives rise to fleeting perceptions of happiness and distress. These are non-permanent; they come and go. Bear them patiently.", themes: ["impermanence", "equanimity", "patience", "emotions"], moods: ["sad", "frustrated", "anxious", "angry"] },
  { ref: "2.20", text: "The soul is never born and never dies; nor does it come into being only once. It is unborn, eternal, ever-existing, and primeval. It is not slain when the body is slain.", themes: ["eternal", "soul", "fearlessness"], moods: ["sad", "anxious", "lonely"] },
  { ref: "2.22", text: "As a person puts on new garments, giving up old ones, the soul similarly accepts new material bodies, giving up the old and useless ones.", themes: ["change", "renewal", "acceptance"], moods: ["sad", "anxious", "hopeful"] },
  { ref: "2.27", text: "For one who has taken birth, death is certain; and for one who is dead, birth is certain. Therefore, in the unavoidable discharge of your duty, you should not grieve.", themes: ["acceptance", "duty", "cycle"], moods: ["sad", "overwhelmed", "confused"] },
  { ref: "2.38", text: "Fight for the sake of duty, treating alike happiness and distress, loss and gain, victory and defeat. Fulfill your duty, and you shall not incur sin.", themes: ["duty", "equanimity", "action"], moods: ["confused", "anxious", "frustrated"] },
  { ref: "2.47", text: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself to be the cause of the results, nor be attached to inaction.", themes: ["non-attachment", "duty", "action", "control"], moods: ["anxious", "overwhelmed", "restless", "confused"] },
  { ref: "2.48", text: "Perform your duty equipoised, O Arjuna, abandoning all attachment to success or failure. Such equanimity is called yoga.", themes: ["equanimity", "yoga", "balance"], moods: ["anxious", "restless", "overwhelmed"] },
  { ref: "2.50", text: "A person engaged in devotional service rids himself of both good and bad reactions even in this life. Therefore strive for yoga, which is the art of all work.", themes: ["action", "yoga", "skill"], moods: ["confused", "restless", "hopeful"] },
  { ref: "2.55", text: "When a man completely casts off all the desires of the mind, and is satisfied in the Self by the Self, then he is said to be of steady wisdom.", themes: ["peace", "contentment", "wisdom", "desire"], moods: ["restless", "anxious", "overwhelmed"] },
  { ref: "2.56", text: "One whose mind is undisturbed by distress, who has no desire for pleasure, and who is free from attachment, fear, and anger, is called a sage of steady mind.", themes: ["equanimity", "peace", "non-attachment"], moods: ["angry", "anxious", "frustrated"] },
  { ref: "2.62", text: "While contemplating the objects of the senses, a person develops attachment for them, and from such attachment lust develops, and from lust anger arises.", themes: ["desire", "anger", "awareness", "chain"], moods: ["angry", "restless", "frustrated"] },
  { ref: "2.63", text: "From anger, complete delusion arises, and from delusion bewilderment of memory. When memory is bewildered, intelligence is lost, and when intelligence is lost one falls down again into the material pool.", themes: ["anger", "delusion", "awareness"], moods: ["angry", "confused", "overwhelmed"] },
  { ref: "2.70", text: "A person who is not disturbed by the incessant flow of desires — that enter like rivers into the ocean, which is ever being filled but is always still — can alone achieve peace.", themes: ["peace", "acceptance", "desire", "stillness"], moods: ["restless", "anxious", "overwhelmed"] },

  // Chapter 3 - Karma Yoga
  { ref: "3.5", text: "Everyone is forced to act helplessly according to the qualities he has acquired from the modes of material nature; therefore, no one can refrain from doing something, not even for a moment.", themes: ["action", "nature", "movement"], moods: ["restless", "confused", "frustrated"] },
  { ref: "3.19", text: "Therefore, without being attached to the fruits of activities, one should act as a matter of duty, for by working without attachment one attains the Supreme.", themes: ["duty", "non-attachment", "work", "purpose"], moods: ["confused", "anxious", "restless"] },
  { ref: "3.21", text: "Whatever action a great man performs, common men follow. And whatever standards he sets by exemplary acts, all the world pursues.", themes: ["leadership", "example", "responsibility"], moods: ["confused", "hopeful", "restless"] },
  { ref: "3.27", text: "The bewildered spirit soul, under the influence of the three modes of material nature, thinks himself the doer of activities that are in actuality carried out by nature.", themes: ["ego", "humility", "nature"], moods: ["frustrated", "overwhelmed", "confused"] },
  { ref: "3.30", text: "Therefore, dedicating all your works to Me, with mind intent on the Self, free from desire and selfishness, fight without being lethargic.", themes: ["surrender", "selflessness", "duty", "action"], moods: ["overwhelmed", "confused", "restless"] },
  { ref: "3.35", text: "It is far better to perform one's own duty imperfectly than to assume another's duty perfectly. Destruction in one's own duty is better than engaging in another's, for to follow another's path is dangerous.", themes: ["authenticity", "duty", "comparison", "purpose"], moods: ["confused", "restless", "hopeful"] },

  // Chapter 4 - Knowledge & Renunciation
  { ref: "4.7", text: "Whenever and wherever there is a decline in righteousness and an increase in unrighteousness, at that time I manifest Myself on earth.", themes: ["justice", "hope", "divine", "protection"], moods: ["hopeful", "sad", "confused"] },
  { ref: "4.18", text: "One who sees inaction in action and action in inaction is intelligent among men, and he is in the transcendental position, although engaged in all sorts of activities.", themes: ["wisdom", "action", "perception"], moods: ["confused", "restless", "peaceful"] },
  { ref: "4.22", text: "He who is satisfied with gain which comes of its own accord, who is free from duality, who is free from envy, and who is steady in both success and failure, is never entangled, although performing actions.", themes: ["contentment", "equanimity", "freedom"], moods: ["anxious", "restless", "hopeful"] },
  { ref: "4.33", text: "O Arjuna, the sacrifice of knowledge is greater than the sacrifice of material possessions. All work, without exception, culminates in knowledge.", themes: ["knowledge", "wisdom", "learning"], moods: ["confused", "hopeful", "restless"] },
  { ref: "4.38", text: "In this world, there is nothing as purifying as divine knowledge. One who has attained purity of mind through prolonged practice of yoga finds this knowledge arising within, in due course of time.", themes: ["knowledge", "purity", "practice", "patience"], moods: ["confused", "hopeful", "restless"] },

  // Chapter 5 - Renunciation of Action
  { ref: "5.10", text: "One who performs duty without attachment, surrendering the results unto the Supreme Lord, is unaffected by sinful action, as the lotus leaf is untouched by water.", themes: ["non-attachment", "purity", "duty"], moods: ["anxious", "overwhelmed", "peaceful"] },
  { ref: "5.18", text: "The humble sages, by virtue of true knowledge, see with equal vision a learned scholar, a cow, an elephant, a dog, and an outcast.", themes: ["equality", "wisdom", "compassion", "humility"], moods: ["angry", "frustrated", "peaceful"] },
  { ref: "5.22", text: "An intelligent person does not take part in the sources of misery, which are due to contact with the material senses. Such pleasures have a beginning and an end, and so the wise man does not delight in them.", themes: ["discernment", "pleasure", "wisdom"], moods: ["restless", "anxious", "overwhelmed"] },

  // Chapter 6 - The Yoga of Meditation
  { ref: "6.5", text: "Elevate yourself through the power of your mind, and not degrade yourself, for the mind can be the friend and also the enemy of the self.", themes: ["mind", "self-mastery", "choice", "empowerment"], moods: ["sad", "frustrated", "overwhelmed", "hopeful"] },
  { ref: "6.6", text: "For him who has conquered the mind, the mind is the best of friends; but for one who has failed to do so, his very mind will be the greatest enemy.", themes: ["mind", "discipline", "self-mastery"], moods: ["frustrated", "overwhelmed", "anxious"] },
  { ref: "6.9", text: "A person is considered still further advanced when he regards honest well-wishers, affectionate benefactors, the neutral, mediators, the envious, friends and enemies, the pious and the sinners all with an equal mind.", themes: ["equanimity", "compassion", "maturity"], moods: ["angry", "frustrated", "peaceful"] },
  { ref: "6.17", text: "He who is regulated in his habits of eating, sleeping, recreation, and work can mitigate all material pains by practicing the yoga system.", themes: ["balance", "discipline", "wellness", "moderation"], moods: ["overwhelmed", "restless", "anxious"] },
  { ref: "6.19", text: "As a lamp in a windless place does not waver, so the transcendentalist whose mind is controlled remains always steady in his meditation on the Self.", themes: ["focus", "meditation", "stillness", "concentration"], moods: ["restless", "anxious", "overwhelmed"] },
  { ref: "6.25", text: "Gradually, step by step, one should become situated in trance by means of intelligence sustained by full conviction, and thus the mind should be fixed on the Self alone and should think of nothing else.", themes: ["meditation", "patience", "focus", "gradual"], moods: ["restless", "anxious", "overwhelmed"] },
  { ref: "6.26", text: "From whatever and wherever the mind wanders due to its flickering and unsteady nature, one must certainly withdraw it and bring it back under the control of the Self.", themes: ["focus", "meditation", "mind-control", "practice"], moods: ["restless", "anxious", "overwhelmed", "confused"] },
  { ref: "6.34", text: "The mind is restless, turbulent, obstinate, and very strong, O Krishna, and to subdue it, I think, is more difficult than controlling the wind.", themes: ["mind", "struggle", "honesty", "difficulty"], moods: ["frustrated", "overwhelmed", "anxious"] },
  { ref: "6.35", text: "It is undoubtedly very difficult to curb the restless mind, but it is possible by constant practice and by detachment.", themes: ["practice", "non-attachment", "persistence", "mind-control"], moods: ["frustrated", "overwhelmed", "hopeful"] },

  // Chapter 7-9
  { ref: "7.8", text: "I am the taste of water, the light of the sun and the moon, the syllable om in the Vedic mantras; I am the sound in ether and ability in man.", themes: ["divine", "presence", "awareness", "interconnection"], moods: ["grateful", "peaceful", "hopeful"] },
  { ref: "8.7", text: "Therefore, at all times remember Me and fight. With your mind and intellect fixed on Me, you will certainly come to Me.", themes: ["devotion", "purpose", "focus", "action"], moods: ["confused", "restless", "hopeful"] },
  { ref: "9.22", text: "To those who are constantly devoted and who worship Me with love, I give the understanding by which they can come to Me.", themes: ["devotion", "guidance", "love", "wisdom"], moods: ["lonely", "hopeful", "grateful"] },
  { ref: "9.27", text: "Whatever you do, whatever you eat, whatever you offer or give away, and whatever austerities you perform — do that as an offering to Me.", themes: ["surrender", "purpose", "daily-practice", "offering"], moods: ["confused", "peaceful", "hopeful"] },

  // Chapter 10-12
  { ref: "10.10", text: "To those who are constantly devoted to serving Me with love, I give the understanding by which they can come to Me.", themes: ["devotion", "service", "wisdom", "guidance"], moods: ["lonely", "hopeful", "grateful"] },
  { ref: "11.33", text: "Therefore get up. Prepare to fight and win glory. Conquer your enemies and enjoy a flourishing kingdom. They are already put to death by My arrangement, and you, O Savyasaci, can be but an instrument in the fight.", themes: ["action", "purpose", "instrument", "surrender"], moods: ["overwhelmed", "confused", "hopeful"] },
  { ref: "12.13", text: "One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor and is free from false ego, who is equal in both happiness and distress, who is tolerant and always satisfied, self-controlled, and engaged in devotional service with determination — such a person is very dear to Me.", themes: ["compassion", "humility", "equanimity", "kindness"], moods: ["angry", "frustrated", "peaceful", "grateful"] },
  { ref: "12.15", text: "He for whom no one is put into difficulty and who is not disturbed by anyone, who is equipoised in happiness and distress, fear and anxiety, is very dear to Me.", themes: ["equanimity", "peace", "non-disturbance"], moods: ["anxious", "frustrated", "peaceful"] },

  // Chapter 13-15
  { ref: "13.28", text: "One who sees the Supreme Lord dwelling equally in all beings, the imperishable within the perishable, truly sees.", themes: ["unity", "perception", "divine", "equality"], moods: ["lonely", "confused", "peaceful"] },
  { ref: "14.22", text: "He who does not hate illumination, attachment, and delusion when they are present or long for them when they disappear; who is seated as if unconcerned, being situated beyond these material reactions — such a person is said to have transcended the modes of nature.", themes: ["transcendence", "equanimity", "non-attachment"], moods: ["restless", "anxious", "peaceful"] },
  { ref: "15.5", text: "Those who are free from false prestige, illusion, and false association, who understand the eternal, who are done with material lust, who are freed from the dualities of happiness and distress, and who, unbewildered, know how to surrender unto the Supreme Person, attain to that eternal kingdom.", themes: ["liberation", "wisdom", "surrender", "freedom"], moods: ["confused", "hopeful", "peaceful"] },

  // Chapter 16-18
  { ref: "16.1", text: "The Supreme Lord said: Fearlessness, purification of one's existence, cultivation of spiritual knowledge, charity, self-control, performance of sacrifice, study of the Vedas, austerity, and simplicity are the divine qualities.", themes: ["virtues", "character", "growth", "fearlessness"], moods: ["hopeful", "confused", "restless"] },
  { ref: "16.3", text: "Nonviolence, truthfulness, freedom from anger, renunciation, tranquility, aversion to fault-finding, compassion for all living entities, freedom from covetousness, gentleness, modesty, and steady determination.", themes: ["virtues", "compassion", "truth", "character"], moods: ["angry", "restless", "hopeful"] },
  { ref: "17.3", text: "The faith of each is in accordance with one's own nature. A person is known by the faith they hold. One can become whatever one wants to be if one constantly contemplates on the object of desire.", themes: ["faith", "nature", "becoming", "intention"], moods: ["confused", "hopeful", "restless"] },
  { ref: "18.20", text: "That knowledge by which one undivided spiritual nature is seen in all living entities, though they are divided into innumerable forms, know that knowledge to be in the mode of goodness.", themes: ["unity", "wisdom", "perception", "goodness"], moods: ["lonely", "confused", "peaceful"] },
  { ref: "18.37", text: "That which in the beginning may be just like poison but at the end is just like nectar and which awakens one to self-realization is said to be happiness in the mode of goodness.", themes: ["perseverance", "delayed-gratification", "growth", "happiness"], moods: ["frustrated", "sad", "hopeful"] },
  { ref: "18.46", text: "By worship of the Lord, who is the source of all beings and who is all-pervading, a man can attain perfection through performing his own work.", themes: ["purpose", "work", "devotion", "perfection"], moods: ["confused", "restless", "hopeful"] },
  { ref: "18.48", text: "Every endeavor is covered by some fault, just as fire is covered by smoke. Therefore one should not give up the work born of his nature, even if such work is full of fault.", themes: ["imperfection", "duty", "acceptance", "persistence"], moods: ["frustrated", "overwhelmed", "sad"] },
  { ref: "18.54", text: "One who is thus transcendentally situated at once realizes the Supreme Brahman and becomes fully joyful. He never laments or desires to have anything. He is equally disposed toward every living entity.", themes: ["liberation", "joy", "equanimity", "peace"], moods: ["sad", "lonely", "peaceful", "hopeful"] },
  { ref: "18.58", text: "If you become conscious of Me, you will pass over all the obstacles of conditioned life by My grace. If, however, you do not work in such consciousness but act through false ego, not hearing Me, you will be lost.", themes: ["surrender", "grace", "ego", "consciousness"], moods: ["overwhelmed", "confused", "hopeful"] },
  { ref: "18.63", text: "Thus I have explained to you knowledge still more confidential. Deliberate on this fully, and then do what you wish to do.", themes: ["freedom", "choice", "wisdom", "autonomy"], moods: ["confused", "hopeful", "peaceful"] },
  { ref: "18.65", text: "Always think of Me, become My devotee, worship Me and offer your homage unto Me. Thus you will come to Me without fail. I promise you this because you are My very dear friend.", themes: ["devotion", "friendship", "divine", "love"], moods: ["lonely", "sad", "hopeful", "grateful"] },
  { ref: "18.66", text: "Abandon all varieties of duty and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear.", themes: ["surrender", "fearlessness", "trust", "grace"], moods: ["anxious", "overwhelmed", "hopeful", "confused"] },
  { ref: "18.78", text: "Wherever there is Krishna, the master of all mystics, and wherever there is Arjuna, the supreme archer, there will also certainly be opulence, victory, extraordinary power, and morality.", themes: ["victory", "purpose", "divine-partnership", "morality"], moods: ["hopeful", "grateful", "peaceful"] },
];

// ==========================================
// STOIC PASSAGES (50+)
// ==========================================
const stoicPassages = [
  // Marcus Aurelius - Meditations
  { source: "Marcus Aurelius, Meditations", ref: "2.1", text: "Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness — all of them due to the offenders' ignorance of what is good or evil.", themes: ["preparation", "acceptance", "resilience", "morning"], moods: ["anxious", "frustrated", "overwhelmed"] },
  { source: "Marcus Aurelius, Meditations", ref: "2.4", text: "Think of your many years of procrastination; how the gods have repeatedly granted you further periods of grace, of which you have taken no advantage. It is time now to realize the nature of the universe to which you belong.", themes: ["urgency", "procrastination", "awareness", "time"], moods: ["restless", "confused", "overwhelmed"] },
  { source: "Marcus Aurelius, Meditations", ref: "2.14", text: "Even if you were to live three thousand years, remember that no one loses any life other than the one currently being lived. The longest and shortest lives amount to the same thing.", themes: ["present-moment", "impermanence", "perspective"], moods: ["anxious", "overwhelmed", "sad"] },
  { source: "Marcus Aurelius, Meditations", ref: "4.3", text: "People look for retreats for themselves — in the country, by the coast, in the mountains. But this is altogether unphilosophical. You can retreat into yourself at any time you want.", themes: ["inner-peace", "retreat", "self-sufficiency"], moods: ["overwhelmed", "restless", "anxious"] },
  { source: "Marcus Aurelius, Meditations", ref: "4.7", text: "Choose not to be harmed — and you won't feel harmed. Don't feel harmed — and you haven't been.", themes: ["perception", "choice", "resilience", "power"], moods: ["angry", "frustrated", "sad"] },
  { source: "Marcus Aurelius, Meditations", ref: "5.16", text: "The things you think about determine the quality of your mind. Your soul takes on the color of your thoughts.", themes: ["mind", "thoughts", "quality", "awareness"], moods: ["anxious", "restless", "confused"] },
  { source: "Marcus Aurelius, Meditations", ref: "5.20", text: "The impediment to action advances action. What stands in the way becomes the way.", themes: ["obstacle", "opportunity", "resilience", "growth"], moods: ["frustrated", "overwhelmed", "hopeful"] },
  { source: "Marcus Aurelius, Meditations", ref: "6.6", text: "The best revenge is not to be like your enemy.", themes: ["character", "revenge", "integrity", "dignity"], moods: ["angry", "frustrated", "sad"] },
  { source: "Marcus Aurelius, Meditations", ref: "6.15", text: "Do not indulge in dreams of having what you have not, but reckon up the chief of the blessings you do possess, and then thankfully remember how you would crave them if they were not yours.", themes: ["gratitude", "contentment", "perspective"], moods: ["sad", "restless", "grateful"] },
  { source: "Marcus Aurelius, Meditations", ref: "7.9", text: "Never value anything as profitable that compels you to break your promise, to lose your self-respect, to hate any man, to suspect, to curse, to act the hypocrite.", themes: ["integrity", "values", "character"], moods: ["confused", "frustrated", "restless"] },
  { source: "Marcus Aurelius, Meditations", ref: "7.59", text: "Look within. Within is the fountain of good, and it will ever bubble up, if you will ever dig.", themes: ["inner-wisdom", "self-discovery", "potential"], moods: ["sad", "lonely", "confused", "hopeful"] },
  { source: "Marcus Aurelius, Meditations", ref: "8.47", text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.", themes: ["perception", "control", "power", "freedom"], moods: ["anxious", "frustrated", "overwhelmed", "angry"] },
  { source: "Marcus Aurelius, Meditations", ref: "9.29", text: "Do not waste what remains of your life in speculating about your neighbors. Anything that distracts you from fidelity to the Ruler within you means a loss of opportunity.", themes: ["focus", "comparison", "attention", "purpose"], moods: ["restless", "anxious", "confused"] },
  { source: "Marcus Aurelius, Meditations", ref: "10.16", text: "No longer talk at all about the kind of person that a good person ought to be, but simply be such a person.", themes: ["action", "authenticity", "integrity", "simplicity"], moods: ["confused", "restless", "hopeful"] },
  { source: "Marcus Aurelius, Meditations", ref: "11.18", text: "How much more grievous are the consequences of anger than the causes of it.", themes: ["anger", "consequences", "patience", "perspective"], moods: ["angry", "frustrated"] },
  { source: "Marcus Aurelius, Meditations", ref: "12.26", text: "When you are troubled about something, you have forgotten that all things happen according to the universal nature.", themes: ["acceptance", "nature", "trust", "perspective"], moods: ["anxious", "overwhelmed", "confused"] },

  // Epictetus - Enchiridion & Discourses
  { source: "Epictetus, Enchiridion", ref: "Chapter 1", text: "Some things are within our power, while others are not. Within our power are opinion, motivation, desire, aversion, and whatever is of our own doing; not within our power are our body, our property, reputation, office, and whatever is not of our own doing.", themes: ["control", "acceptance", "power", "dichotomy"], moods: ["anxious", "overwhelmed", "frustrated", "confused"] },
  { source: "Epictetus, Enchiridion", ref: "Chapter 5", text: "Men are disturbed not by things, but by the views which they take of things.", themes: ["perception", "mind", "freedom", "choice"], moods: ["anxious", "angry", "frustrated", "overwhelmed"] },
  { source: "Epictetus, Enchiridion", ref: "Chapter 8", text: "Don't demand that things happen as you wish, but wish that they happen as they do happen, and you will go on well.", themes: ["acceptance", "peace", "adaptability", "surrender"], moods: ["frustrated", "angry", "overwhelmed", "anxious"] },
  { source: "Epictetus, Enchiridion", ref: "Chapter 10", text: "With every accident, ask yourself what ability you have for making proper use of it.", themes: ["opportunity", "resilience", "resourcefulness"], moods: ["frustrated", "overwhelmed", "sad"] },
  { source: "Epictetus, Enchiridion", ref: "Chapter 15", text: "Remember that you must behave in life as at a dinner party. Is anything brought around to you? Put out your hand and take your share with moderation.", themes: ["moderation", "contentment", "gratitude"], moods: ["restless", "anxious", "grateful"] },
  { source: "Epictetus, Enchiridion", ref: "Chapter 33", text: "Silence is preferable to meaningless words. Say only what is necessary and be brief about it.", themes: ["silence", "speech", "wisdom", "restraint"], moods: ["restless", "anxious", "peaceful"] },
  { source: "Epictetus, Discourses", ref: "1.1", text: "Of all existing things some are in our power, and others are not in our power.", themes: ["control", "dichotomy", "power", "acceptance"], moods: ["anxious", "overwhelmed", "confused"] },
  { source: "Epictetus, Discourses", ref: "2.5", text: "It is not what happens to you, but how you react to it that matters.", themes: ["response", "control", "choice", "resilience"], moods: ["angry", "frustrated", "overwhelmed", "sad"] },
  { source: "Epictetus, Discourses", ref: "3.10", text: "If you want to improve, be content to be thought foolish and stupid with regard to external things.", themes: ["growth", "humility", "courage", "non-attachment"], moods: ["confused", "frustrated", "hopeful"] },

  // Seneca - Letters & Essays
  { source: "Seneca, Letters to Lucilius", ref: "Letter 1", text: "It is not that we have a short time to live, but that we waste a great deal of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.", themes: ["time", "purpose", "urgency", "waste"], moods: ["restless", "overwhelmed", "confused"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 12", text: "Let us prepare our minds as if we had come to the very end of life. Let us postpone nothing. Let us balance life's books each day.", themes: ["memento-mori", "urgency", "presence", "balance"], moods: ["restless", "overwhelmed", "anxious"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 13", text: "We suffer more often in imagination than in reality.", themes: ["anxiety", "imagination", "present-moment", "fear"], moods: ["anxious", "overwhelmed", "restless"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 22", text: "It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult.", themes: ["courage", "fear", "action", "difficulty"], moods: ["anxious", "overwhelmed", "frustrated"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 28", text: "No person has the power to have everything they want, but it is in their power not to want what they don't have, and to cheerfully put to good use what they do have.", themes: ["contentment", "gratitude", "power", "acceptance"], moods: ["sad", "restless", "grateful"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 47", text: "Associate with people who are likely to improve you. Welcome those who you are capable of improving. The process is a mutual one: men learn as they teach.", themes: ["community", "growth", "teaching", "learning"], moods: ["lonely", "hopeful", "restless"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 49", text: "While we wait for life, life passes.", themes: ["urgency", "presence", "time", "action"], moods: ["restless", "overwhelmed", "anxious"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 71", text: "Sometimes even to live is an act of courage.", themes: ["courage", "resilience", "suffering", "strength"], moods: ["sad", "overwhelmed", "lonely"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 78", text: "It is during sickness that you will discover whether what you have been practicing is true or not.", themes: ["adversity", "character", "truth", "testing"], moods: ["sad", "overwhelmed", "frustrated"] },
  { source: "Seneca, Letters to Lucilius", ref: "Letter 88", text: "The willing are led by fate, the unwilling are dragged.", themes: ["acceptance", "resistance", "flow", "surrender"], moods: ["frustrated", "overwhelmed", "anxious"] },
  { source: "Seneca, On Anger", ref: "2.29", text: "The greatest remedy for anger is delay.", themes: ["anger", "patience", "delay", "control"], moods: ["angry", "frustrated", "restless"] },
  { source: "Seneca, On Anger", ref: "3.36", text: "Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it.", themes: ["anger", "self-harm", "control", "perspective"], moods: ["angry", "frustrated"] },
  { source: "Seneca, On the Shortness of Life", ref: "Chapter 1", text: "It is not that we have a short time to live, but that we waste much of it. Life is long if you know how to use it.", themes: ["time", "purpose", "awareness", "living"], moods: ["restless", "overwhelmed", "confused"] },
  { source: "Seneca, On the Shortness of Life", ref: "Chapter 3", text: "People are frugal in guarding their personal property; but as soon as it comes to squandering time they are most wasteful of the one thing in which it is right to be stingy.", themes: ["time", "priority", "waste", "awareness"], moods: ["restless", "overwhelmed", "anxious"] },
  { source: "Seneca, On the Shortness of Life", ref: "Chapter 9", text: "The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.", themes: ["present-moment", "expectation", "today", "presence"], moods: ["anxious", "restless", "overwhelmed"] },
  { source: "Seneca, Moral Letters", ref: "Letter 16", text: "We should every night call ourselves to account: What infirmity have I mastered today? What passions opposed? What temptation resisted? What virtue acquired?", themes: ["reflection", "self-examination", "growth", "evening"], moods: ["restless", "hopeful", "peaceful"] },
];

// ==========================================
// BUDDHIST WISDOM (30+)
// ==========================================
const buddhistVerses = [
  // Dhammapada
  { source: "Dhammapada", ref: "Verse 1", text: "All that we are is the result of what we have thought: it is founded on our thoughts, it is made up of our thoughts. If a man speaks or acts with a pure thought, happiness follows him like a shadow that never leaves him.", themes: ["mind", "thoughts", "karma", "happiness"], moods: ["confused", "sad", "hopeful"] },
  { source: "Dhammapada", ref: "Verse 2", text: "All that we are is the result of what we have thought: if a man speaks or acts with an evil thought, pain follows him as the wheel follows the foot of the ox that draws the carriage.", themes: ["karma", "consequences", "mind", "intention"], moods: ["frustrated", "angry", "confused"] },
  { source: "Dhammapada", ref: "Verse 5", text: "Hatred does not cease by hatred, but only by love; this is the eternal rule.", themes: ["love", "hatred", "compassion", "peace"], moods: ["angry", "frustrated", "sad"] },
  { source: "Dhammapada", ref: "Verse 17", text: "The evil-doer suffers in this world, and he suffers in the next; he suffers in both. He suffers when he thinks of the evil he has done; he suffers more when going on the evil path.", themes: ["karma", "suffering", "ethics", "awareness"], moods: ["frustrated", "sad", "confused"] },
  { source: "Dhammapada", ref: "Verse 21", text: "Earnestness is the path of immortality. Sloth is the path of death. Those who are earnest do not die, while those who are slothful are as if dead already.", themes: ["effort", "awareness", "presence", "earnestness"], moods: ["restless", "overwhelmed", "confused"] },
  { source: "Dhammapada", ref: "Verse 33", text: "As a fletcher makes straight his arrow, a wise man makes straight his trembling and unsteady thought, which is difficult to guard, difficult to hold back.", themes: ["mind-control", "focus", "discipline", "practice"], moods: ["restless", "anxious", "overwhelmed"] },
  { source: "Dhammapada", ref: "Verse 50", text: "Let none find fault with others; let none see the omissions and commissions of others. But let one see one's own acts, done and undone.", themes: ["self-awareness", "judgment", "focus-inward", "responsibility"], moods: ["angry", "frustrated", "restless"] },
  { source: "Dhammapada", ref: "Verse 76", text: "If you see a wise person who points out your faults and corrects you, follow that wise person as you would a guide to hidden treasure.", themes: ["wisdom", "feedback", "growth", "humility"], moods: ["confused", "frustrated", "hopeful"] },
  { source: "Dhammapada", ref: "Verse 103", text: "Greater in battle than the man who would conquer a thousand men, is he who would conquer just one — himself.", themes: ["self-mastery", "victory", "inner-battle", "strength"], moods: ["frustrated", "overwhelmed", "restless"] },
  { source: "Dhammapada", ref: "Verse 160", text: "One truly is the protector of oneself; who else could the protector be? With oneself fully controlled, one gains a mastery that is hard to gain.", themes: ["self-reliance", "discipline", "mastery", "responsibility"], moods: ["lonely", "overwhelmed", "frustrated"] },
  { source: "Dhammapada", ref: "Verse 170", text: "Look upon the world as a bubble, look upon it as a mirage: the king of death does not see him who thus looks upon the world.", themes: ["impermanence", "illusion", "perspective", "freedom"], moods: ["anxious", "overwhelmed", "sad"] },
  { source: "Dhammapada", ref: "Verse 183", text: "Not to do any evil, to cultivate the good, to purify one's mind — this is the teaching of all the Buddhas.", themes: ["goodness", "purity", "ethics", "simplicity"], moods: ["confused", "hopeful", "peaceful"] },
  { source: "Dhammapada", ref: "Verse 197", text: "Happy indeed we live, friendly amidst the hostile. Amidst hostile men let us dwell free from hatred.", themes: ["peace", "love", "hatred", "freedom"], moods: ["angry", "frustrated", "peaceful"] },
  { source: "Dhammapada", ref: "Verse 218", text: "He whose longing has been aroused for the indescribable, whose mind has been filled with the thought of it, and whose thought is not attached to sensual pleasures, such a person is called one who goes upstream.", themes: ["aspiration", "non-attachment", "transcendence", "growth"], moods: ["restless", "hopeful", "confused"] },
  { source: "Dhammapada", ref: "Verse 239", text: "By degrees, little by little, from moment to moment, a wise person removes their own impurities, as a smith removes the dross of silver.", themes: ["gradual-progress", "patience", "purification", "practice"], moods: ["frustrated", "overwhelmed", "hopeful"] },
  { source: "Dhammapada", ref: "Verse 276", text: "You yourselves must strive; the Buddhas only point the way. Those who have entered the path and who meditate will be freed from the chains of illusion.", themes: ["self-effort", "path", "meditation", "freedom"], moods: ["confused", "restless", "hopeful"] },
  { source: "Dhammapada", ref: "Verse 277", text: "All conditioned things are impermanent — when one sees this with wisdom, one turns away from suffering. This is the path to purification.", themes: ["impermanence", "wisdom", "suffering", "liberation"], moods: ["sad", "anxious", "overwhelmed"] },
  { source: "Dhammapada", ref: "Verse 334", text: "The craving of a person who lives heedlessly grows like a creeping vine. They run from life to life, like a monkey seeking fruit in the forest.", themes: ["craving", "mindfulness", "desire", "awareness"], moods: ["restless", "anxious", "overwhelmed"] },
  { source: "Dhammapada", ref: "Verse 381", text: "A monk who delights in awareness, who regards heedlessness with fear, advances like fire, burning all fetters, great and small.", themes: ["mindfulness", "progress", "liberation", "awareness"], moods: ["restless", "hopeful", "confused"] },

  // Key Buddhist Teachings
  { source: "The Four Noble Truths", ref: "First Noble Truth", text: "Life involves suffering (dukkha). This is not pessimism — it is the recognition that dissatisfaction, impermanence, and change are inherent in existence.", themes: ["suffering", "truth", "acceptance", "reality"], moods: ["sad", "overwhelmed", "confused"] },
  { source: "The Four Noble Truths", ref: "Second Noble Truth", text: "The origin of suffering is craving (tanha) — the thirst for pleasure, for existence, for non-existence. It is attachment that binds us to the cycle.", themes: ["craving", "attachment", "origin", "awareness"], moods: ["restless", "anxious", "overwhelmed"] },
  { source: "The Four Noble Truths", ref: "Third Noble Truth", text: "The cessation of suffering is attainable. By letting go of craving and attachment, one can reach a state of liberation and inner peace.", themes: ["liberation", "peace", "letting-go", "hope"], moods: ["sad", "overwhelmed", "hopeful"] },
  { source: "The Four Noble Truths", ref: "Fourth Noble Truth", text: "The path to the cessation of suffering is the Noble Eightfold Path: right view, right intention, right speech, right action, right livelihood, right effort, right mindfulness, right concentration.", themes: ["path", "practice", "discipline", "freedom"], moods: ["confused", "hopeful", "restless"] },
  { source: "Thich Nhat Hanh", ref: "The Miracle of Mindfulness", text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", themes: ["mindfulness", "breath", "impermanence", "present-moment"], moods: ["anxious", "overwhelmed", "restless"] },
  { source: "Thich Nhat Hanh", ref: "Being Peace", text: "Smile, breathe, and go slowly. There is no way to happiness — happiness is the way.", themes: ["happiness", "presence", "simplicity", "peace"], moods: ["anxious", "restless", "overwhelmed"] },
  { source: "Pema Chödrön", ref: "When Things Fall Apart", text: "Nothing ever goes away until it has taught us what we need to know.", themes: ["lessons", "persistence", "growth", "acceptance"], moods: ["frustrated", "sad", "overwhelmed"] },
  { source: "Heart Sutra", ref: "Key passage", text: "Form is emptiness; emptiness is form. Emptiness is not separate from form; form is not separate from emptiness.", themes: ["emptiness", "form", "non-duality", "ultimate-reality"], moods: ["confused", "peaceful", "hopeful"] },
];

// ==========================================
// YOGA SUTRAS OF PATANJALI (20+)
// ==========================================
const yogaSutras = [
  { ref: "1.2", text: "Yoga is the cessation of the fluctuations of the mind.", themes: ["mind-control", "yoga", "stillness", "definition"], moods: ["restless", "anxious", "overwhelmed"] },
  { ref: "1.3", text: "Then the seer abides in its own nature.", themes: ["self", "awareness", "peace", "identity"], moods: ["confused", "lonely", "peaceful"] },
  { ref: "1.12", text: "These mental modifications are restrained by practice and non-attachment.", themes: ["practice", "non-attachment", "discipline", "mind"], moods: ["restless", "anxious", "overwhelmed"] },
  { ref: "1.13", text: "Of these two, practice is the effort to be firmly established in the restraining of the mind's modifications.", themes: ["practice", "effort", "consistency", "discipline"], moods: ["restless", "overwhelmed", "frustrated"] },
  { ref: "1.14", text: "Practice becomes firmly grounded when it has been cultivated for a long time, uninterruptedly, with earnest devotion.", themes: ["persistence", "devotion", "long-term", "consistency"], moods: ["frustrated", "overwhelmed", "hopeful"] },
  { ref: "1.15", text: "Non-attachment is the mastery of consciousness wherein one is free from craving for objects seen or heard about.", themes: ["non-attachment", "freedom", "craving", "mastery"], moods: ["restless", "anxious", "overwhelmed"] },
  { ref: "1.33", text: "By cultivating friendliness toward the happy, compassion for the unhappy, delight in the virtuous, and equanimity toward the non-virtuous, the mind retains its undisturbed calmness.", themes: ["compassion", "equanimity", "relationships", "peace"], moods: ["angry", "frustrated", "lonely", "peaceful"] },
  { ref: "1.34", text: "Or by the exhalation and retention of the breath.", themes: ["breath", "pranayama", "calm", "practice"], moods: ["anxious", "restless", "overwhelmed"] },
  { ref: "2.1", text: "Austerity, self-study, and surrender to God constitute the yoga of action.", themes: ["discipline", "self-study", "surrender", "action"], moods: ["confused", "restless", "hopeful"] },
  { ref: "2.3", text: "The afflictions are ignorance, ego, attachment, aversion, and clinging to life.", themes: ["afflictions", "ignorance", "ego", "attachment"], moods: ["confused", "frustrated", "overwhelmed"] },
  { ref: "2.16", text: "The suffering that has not yet come can be avoided.", themes: ["prevention", "future", "suffering", "hope"], moods: ["anxious", "overwhelmed", "hopeful"] },
  { ref: "2.33", text: "When disturbed by negative thoughts, cultivate the opposite.", themes: ["thought-replacement", "positivity", "practice", "mind"], moods: ["anxious", "sad", "angry", "frustrated"] },
  { ref: "2.46", text: "Posture should be steady and comfortable.", themes: ["balance", "ease", "stability", "comfort"], moods: ["restless", "anxious", "overwhelmed"] },
  { ref: "3.1", text: "Concentration is binding the mind to one place.", themes: ["concentration", "focus", "discipline", "mind"], moods: ["restless", "overwhelmed", "anxious"] },
  { ref: "3.2", text: "Meditation is the uninterrupted flow of awareness toward that point.", themes: ["meditation", "flow", "awareness", "continuity"], moods: ["restless", "overwhelmed", "peaceful"] },
  { ref: "4.3", text: "The incidental cause does not stir the natural tendencies into activity; it merely removes the obstacles, as a farmer irrigates a field by removing the obstacles to the natural flow of water.", themes: ["natural-flow", "obstacles", "effortlessness", "grace"], moods: ["frustrated", "overwhelmed", "hopeful"] },
  { ref: "4.15", text: "Even though the object is the same, the means of cognition being different, the cognitions are different.", themes: ["perception", "subjectivity", "awareness", "mind"], moods: ["confused", "frustrated", "peaceful"] },
];

// Output to stdout as a TypeScript module
console.log("// === GENERATED CONTENT — DO NOT EDIT DIRECTLY ===");
console.log("// Generated by scripts/generate-content.ts");
console.log(`// Gita: ${gitaVerses.length}, Stoic: ${stoicPassages.length}, Buddhist: ${buddhistVerses.length}, Yoga: ${yogaSutras.length}`);
console.log(`// Total verses: ${gitaVerses.length + stoicPassages.length + buddhistVerses.length + yogaSutras.length}`);
console.log("");

// Summary
const total = gitaVerses.length + stoicPassages.length + buddhistVerses.length + yogaSutras.length;
console.error(`Generated: Gita=${gitaVerses.length}, Stoic=${stoicPassages.length}, Buddhist=${buddhistVerses.length}, Yoga=${yogaSutras.length}, Total=${total}`);
